name: Docker Release Workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Get the Git tag
        id: get_tag
        run: |
          TAG="${GITHUB_REF##*/}"
          echo "Tag is: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image using Docker Compose
        run: |
          # Budowanie obrazu z użyciem docker-compose
          docker-compose -f docker-compose.yml build --no-cache

      - name: Tag Docker image as latest
        run: |
          docker tag gesture_controlled_presentation_tool_frontend:latest gesture_controlled_presentation_tool_frontend:latest

      - name: Save Docker image as tar
        run: |
          docker save -o gesture_controlled_presentation_tool_frontend-${{ env.TAG }}.tar gesture_controlled_presentation_tool_frontend:latest

      - name: Zip Docker image
        run: |
          zip gesture_controlled_presentation_tool_frontend-${{ env.TAG }}.zip gesture_controlled_presentation_tool_frontend-${{ env.TAG }}.tar

      - name: Create README file with instructions
        run: |
          echo "To run the application with Docker, follow these steps:" > ToDo.txt
          echo "1. Download and unzip the release file." >> ToDo.txt
          echo "2. Run the following command to load the Docker image:" >> ToDo.txt
          echo "   docker load -i gesture_controlled_presentation_tool_frontend-${{ env.TAG }}.tar" >> ToDo.txt
          echo "3. Start the application by running this command:" >> ToDo.txt
          echo "   docker run -d -p 3000:3000 gesture_controlled_presentation_tool_frontend:latest" >> ToDo.txt
          echo "4. Visit http://localhost:3000 to view the application." >> ToDo.txt

      - name: Create GitHub Release and upload zip and ToDo.txt
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          release_name: "Release ${{ env.TAG }}"
          files: |
            gesture_controlled_presentation_tool_frontend-${{ env.TAG }}.zip
            ToDo.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up
        run: |
          rm gesture_controlled_presentation_tool_frontend-${{ env.TAG }}.tar
          rm gesture_controlled_presentation_tool_frontend-${{ env.TAG }}.zip
          rm ToDo.txt
